name: voice_studio
description: Voice Studio - multilingual translator, speech-to-text and voice generator.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/voice_studio_icon.svg
    - assets/voice_studio_splash.svg

flutter_launcher_icons:
  android: true
  image_path: assets/voice_studio_icon.png
  adaptive_icon_background: "#12C9A0"

flutter_native_splash:
  color: "#F8FFFC"
  image: assets/voice_studio_splash.png
  android_12:
    color: "#F8FFFC"
    image: assets/voice_studio_icon.png
    icon_background_color: "#12C9A0"
